= 1. Introduction

The OGC WMTS Implementation Standard provides an interface to serve digital maps using predefined image tiles. It complements the existing OGC Web Map Service (WMS) standard. As described in Normative Reference [1], “The WMS standard focuses on flexibility in the client request enabling clients to obtain exactly the final map image they want. A WMS client can request that the server creates a map by overlaying an arbitrary number of the map layers offered by the server, over an arbitrary geographic bound, with an arbitrary background color at an arbitrary scale, in any supported coordinate reference system. The client may also request that the map layers be rendered using a specific server advertised style or even use a style provided by the client when the WMS server implements the OGC Styled Layers Descriptor (SLD) standard. However, all this flexibility comes at a price: server image processing must scale with the number of connected clients and there is only limited potential to cache images between the server and client since most images are different”.

The tile resource is generally a rectangular image containing 2D map data. Alternatively, this resource might be a non-image representation of the tile such as a description of the tile or a link to the actual image. For example, the tile resource could be a KML document used in a super-overlay, or a tile metadata document. When returning an image tile, a full single tile will always be returned. Also, the background pixels of a tile should be transparent when possible so that the client can overlay the tiles on top of other map data (possibly other tiles).

To improve performance, instead of creating a new image for each request, a WMTS returns small pre-generated images (e.g., PNG or JPEG) or reuses identical previous requests that follow a set of tile matrices. This standard provides support for multiple architectural patterns - KVP, REST and SOAP. WMTS is the first OGC standard to include a RESTful approach in addition to the usual OGC encodings. Additionally, WMTS provides a natural way to evolve WMS services into a more constrained but more scalable and faster service.
